CREATE TABLE IF NOT EXISTS `onewire` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `family_code` VARCHAR(2) DEFAULT NULL,
  `name` VARCHAR(255) DEFAULT NULL,
  `type` VARCHAR(500) DEFAULT NULL,
  `class` LONGTEXT,
  `link` VARCHAR(500) DEFAULT NULL,
  `groupe` VARCHAR(255) DEFAULT NULL,
  `class2` longtext,
  PRIMARY KEY (`id`)
) ENGINE = INNODB AUTO_INCREMENT = 37 DEFAULT CHARSET = latin1;
CREATE TABLE IF NOT EXISTS `onewire_send_history` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `sensor_id` VARCHAR(255) DEFAULT NULL,
  `sensor_class` VARCHAR(255) DEFAULT NULL,
  `sensor_value` VARCHAR(255) DEFAULT NULL,
  `history_type` VARCHAR(255) DEFAULT NULL,
  `date_add` DATETIME DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE = INNODB AUTO_INCREMENT = 3 DEFAULT CHARSET = latin1;